### PR TITLE
Statusbar button

### PR DESCRIPTION
**Pull request by sketchbuch**
* Added a statusbar button to run the stylizer command on the current file
* Button appears whenever an Editor with the language type "dart" is the active editor
** Added extension dependency to the Dart extension (this adds dart as an editor language)
* Added tests
* Added an activation event for stylizer: When an editor with the language type dart is opened

For people like me who hate the command palette and always forget shortcut keys!

### CODE REVIEW

**Comment by gmlewis** [comment]
Sounds cool, @sketchbuch! I'll check this out and get back to you.

**Comment by gmlewis** [comment]
Hi @sketchbuch - I downloaded your PR and did an `npm install` but then I get two problems in VSCode, both saying: `Type 'SinonSpy' is not generic.`

Screenshot from 2019-07-08 18-51-02

Can you please fix this or let me know if I'm doing something wrong?

Thank you!

**Comment by sketchbuch** [comment]
Hi @gmlewis ,
I updated the types for sinon. when I run tests all pass. Could you try removing your nod_modules folder and redo npm install?

**Review by gmlewis — APPROVED** [review]
That worked great, @sketchbuch!

Thank you very much for adding this really cool feature!

I'll release a new version of the extension after merging.

**Comment by gmlewis** [comment]
Your changes are now live in the marketplace:
https://marketplace.visualstudio.com/items?itemName=gmlewis-vscode.flutter-stylizer
Thanks again, @sketchbuch!

**Comment by sketchbuch** [comment]
Cool! thanks ;)

**Pull request merged**
